# Generated by Django 4.2.18 on 2025-02-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_per_unit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
